# Generated by Django 5.1.5 on 2025-04-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200)),
                ('rok', models.IntegerField()),
                ('reziser', models.CharField(max_length=200)),
                ('zanr', models.CharField(max_length=100)),
                ('hodnoceni', models.FloatField()),
            ],
        ),
    ]
