# Generated by Django 5.1.7 on 2025-04-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='jmeno',
            field=models.CharField(default='jmeno', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='prijmeni',
            field=models.CharField(default='prijmeni', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='director',
            name='rok_narozeni',
            field=models.IntegerField(default='1978'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='reziser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmy', to='movies.director'),
        ),
    ]
