# Generated by Django 5.1.5 on 2025-06-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director_jmeno_director_prijmeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='obrazek',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
